# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='css',
            old_name='recuro',
            new_name='recurso',
        ),
    ]
